remote_theme: poole/poole

# Setup
title:               BBBlog
tagline:             "Yeojeong's Tech Blog"
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://yeojeong998.github.io/poole
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              'Kim, Yeojeong'
  url:               
  email:             yeojeong.kim90@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

